//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "jobx_task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub task_type: i16,
    #[sea_orm(unique_key = "ak_job_id_and_scheduled_exec_start_ms")]
    pub job_id: Option<i64>,
    pub status: i16,
    pub assign_ms: i64,
    #[sea_orm(unique_key = "ak_job_id_and_scheduled_exec_start_ms")]
    pub scheduled_exec_start_ms: Option<i64>,
    pub executor_code: String,
    pub executor_instance: Option<String>,
    pub exec_params: Option<String>,
    pub job_type: i16,
    pub high_freq: Option<bool>,
    pub cron: Option<String>,
    pub interval_duration: Option<String>,
    pub valid_begin_ms: Option<i64>,
    pub valid_end_ms: Option<i64>,
    pub assign_lead_ms: Option<i64>,
    pub exec_detail: Option<String>,
    pub exec_start_ms: Option<i64>,
    pub exec_end_ms: Option<i64>,
    pub creator_id: i64,
    pub create_ms: i64,
    pub updator_id: i64,
    pub update_ms: i64,
    #[sea_orm(
        belongs_to,
        from = "job_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub jobx_job: BelongsTo<Option<super::jobx_job::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}