//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "jobx_job")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    #[sea_orm(unique)]
    pub code: String,
    #[sea_orm(unique)]
    pub name: String,
    pub params: Option<String>,
    pub scheduling_type: i16,
    pub cron: Option<String>,
    pub interval_duration: Option<String>,
    pub valid_begin_ts: Option<i64>,
    pub valid_end_ts: Option<i64>,
    pub next_trigger_ts: Option<i64>,
    pub remark: Option<String>,
    pub enabled: bool,
    pub creator_id: i64,
    pub create_ts: i64,
    pub updator_id: i64,
    pub update_ts: i64,
    #[sea_orm(has_many)]
    pub jobx_tasks: HasMany<super::jobx_task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
